### PR TITLE
correctly handle scientific notations in `isNonNegative`/`isPositive` checks as well

### LINKED ISSUE #276: `hasDataType` and `isNonNegative` checks can get weird with `Fractional` columns
I found those checks can go crazy -- there seem to be at least two problems around them.

1. `isNonNegative` (and `hasDataType(..., ConstrainableDataTypes.Fractional)`) check fails for some reason if the target columns is nullable, which seems to be a bug.

MRE
```scala
import breeze.linalg.{randomInt, randomDouble}
import com.amazon.deequ.checks.{Check, CheckLevel, CheckStatus}
import com.amazon.deequ.constraints.{ConstraintStatus, ConstrainableDataTypes}
import com.amazon.deequ.constraints.Constraint.dataTypeConstraint
import com.amazon.deequ.{VerificationSuite, VerificationResult}
import com.amazon.deequ.VerificationResult.checkResultsAsDataFrame

case class Data ( id: Int, num: String ) // deequ will infer the type of `num` column

val rows = (1 to 10000).map { Data(_, if (randomInt() == 0) null /* or even "0.0" fails */ else randomDouble().toString) }
val rdd = spark.sparkContext.parallelize(rows)
val data = spark.createDataFrame(rdd)

val res = VerificationSuite()
    .onData(data)
    .addCheck(
        Check(CheckLevel.Error, "should be non-negative")
            .hasDataType("num", ConstrainableDataTypes.Fractional)
            .isNonNegative("num")
    )
    .run()
checkResultsAsDataFrame(spark, res).show(Int.MaxValue, false)
```
will yield
```
+----------------------+-----------+------------+----------------------------------------------------------------------------------+-----------------+-------------------------------------------------------------------+
|check                 |check_level|check_status|constraint                                                                        |constraint_status|constraint_message                                                 |
+----------------------+-----------+------------+----------------------------------------------------------------------------------+-----------------+-------------------------------------------------------------------+
|should be non-negative|Error      |Error       |AnalysisBasedConstraint(DataType(num,None),<function1>,Some(<function1>),None)    |Failure          |Value: 0.9988073941562313 does not meet the constraint requirement!|
|should be non-negative|Error      |Error       |ComplianceConstraint(Compliance(num is non-negative,COALESCE(num, 0.0) >= 0,None))|Failure          |Value: 0.9994 does not meet the constraint requirement!            |
+----------------------+-----------+------------+----------------------------------------------------------------------------------+-----------------+-------------------------------------------------------------------+
```

2. `hasDataType(..., ConstrainableDataTypes.Fractional)` check fails even when the target column is `Double`-typed ahead of time:
MRE:
```scala
import breeze.linalg.{randomInt, randomDouble}
import com.amazon.deequ.checks.{Check, CheckLevel, CheckStatus}
import com.amazon.deequ.constraints.{ConstraintStatus, ConstrainableDataTypes}
import com.amazon.deequ.constraints.Constraint.dataTypeConstraint
import com.amazon.deequ.{VerificationSuite, VerificationResult}
import com.amazon.deequ.VerificationResult.checkResultsAsDataFrame

case class Data ( id: Int, num: Double ) // deequ will use native spark data type ?

val rows = (1 to 10000).map { Data(_, randomDouble()) }
val rdd = spark.sparkContext.parallelize(rows)
val data = spark.createDataFrame(rdd)

val res = VerificationSuite()
    .onData(data)
    .addCheck(
        Check(CheckLevel.Error, "should be non-negative")
            .hasDataType("num", ConstrainableDataTypes.Fractional)
            .isNonNegative("num")
    )
    .run()
checkResultsAsDataFrame(spark, res).show(Int.MaxValue, false)
```
will yield
```
+----------------------+-----------+------------+----------------------------------------------------------------------------------+-----------------+------------------------------------------------------+
|check                 |check_level|check_status|constraint                                                                        |constraint_status|constraint_message                                    |
+----------------------+-----------+------------+----------------------------------------------------------------------------------+-----------------+------------------------------------------------------+
|should be non-negative|Error      |Error       |AnalysisBasedConstraint(DataType(num,None),<function1>,Some(<function1>),None)    |Failure          |Value: 0.999 does not meet the constraint requirement!|
|should be non-negative|Error      |Error       |ComplianceConstraint(Compliance(num is non-negative,COALESCE(num, 0.0) >= 0,None))|Success          |                                                      |
+----------------------+-----------+------------+----------------------------------------------------------------------------------+-----------------+------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by aviatesk**
really fixes #276 

- it turns out we need to handle scientific notations in `isNonNegative` and `isPositive` checks as well; this time we need to use `cast(col as decimal(n, n)` to eliminate scientific notations before doing checks
- built on top of #311 (you can see the actual diff from #311 in https://github.com/awslabs/deequ/pull/312/commits/7539fd21213bb8fcffd01a6948bfbc84500766e8)

I'm okay with either of 1.) merge #311 first, and then merge this branch into `master` after rebasing or such, 2.) merge this as is and close #311

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: src/main/scala/com/amazon/deequ/checks/Check.scala [hunk 1]
```diff
@@ -804,8 +804,14 @@ case class Check(
       hint: Option[String] = None)
     : CheckWithLastConstraintFilterable = {
 
-    // coalescing column to not count NULL values as non-compliant
-    satisfies(s"COALESCE($column, 0.0) >= 0", s"$column is non-negative", assertion, hint = hint)
+    satisfies(
+      // coalescing column to not count NULL values as non-compliant
+      // NOTE: cast to DECIMAL(20, 10) is needed to handle scientific notations
+      s"COALESCE(CAST($column as DECIMAL(20,10)), 0.0) >= 0",
```
Comment (aviatesk) [inline src/main/scala/com/amazon/deequ/checks/Check.scala:810]:
```suggestion
      s"COALESCE(CAST($column AS DECIMAL(20,10)), 0.0) >= 0",
```

File: src/main/scala/com/amazon/deequ/checks/Check.scala [hunk 2]
```diff
@@ -822,7 +828,13 @@ case class Check(
       hint: Option[String] = None)
     : CheckWithLastConstraintFilterable = {
     // coalescing column to not count NULL values as non-compliant
-    satisfies(s"COALESCE($column, 1.0) > 0", s"$column is positive", assertion, hint)
+    // NOTE: cast to DECIMAL(20, 10) is needed to handle scientific notations
+    satisfies(
+      s"COALESCE(CAST($column as DECIMAL(20,10)), 1.0) > 0",
```
Comment (aviatesk) [inline src/main/scala/com/amazon/deequ/checks/Check.scala:833]:
```suggestion
      s"COALESCE(CAST($column AS DECIMAL(20,10)), 1.0) > 0",
```

**Comment by sscdotopen** [comment]
@TammoR can you merge this change?

**Comment by aviatesk** [comment]
@twollnik ping, since you're active for this deequ recently, and you seem to have the write access. Could you merge this PR ? We've done a review process with @sscdotopen approving this.
